### ISSUE TITLE
*Lyrics NOT being shown*

### ISSUE THREAD

**Issue by dswapnil104** [SpotX-CLI/SpotX-Linux#12]
## Desktop Client Fails to load lyrics
![spotix-cli-issue](https://user-images.githubusercontent.com/66586954/202858434-0ee7fc03-d7ec-421b-8ec4-40277dbf9e35.png)

- Sys Info : `Pop!_OS 22.04 LTS`
- Spotify-Client : 
  - stable `1:1.1.84.716.gc5f8b819 amd64`
- Operating Country : `India`

Scenario  | Issue
------------- | -------------
Spotify Web Player (Left)  | Lyrics appear as they normally they would.
Debian Desktop Client (Right)  | Desktop client fails to load lyrics altogether.

Intial troubleshooting steps : 
 - [x] Client re-installation
 - [x] User settings cleared from `~/.config/spotify`

### Finally,
Post uninstallation of _SpotX-CLI_ script , lyrics are back to normal.

**Comment by amd64fox** [comment]
fixed

**Comment by dswapnil104** [comment]
### EDIT
Issue fixed with [fix](https://github.com/SpotX-CLI/SpotX-Linux/commit/1e309cf46848e9d10648d841bdbc5c3d158d6654)
