### ISSUE TITLE
Support for Flatpak version?

### ISSUE THREAD

**Issue by frnmz** [SpotX-CLI/SpotX-Linux#20]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of Spotify and SpotX

### Сountry of your account

Indonesia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.1.84.716.gc5f8b819
- Distro: Fedora Linux 37 Silverblue
- Shell: Bash 5.2.9
```

### 📝 Description

Hi, so I tried to use this script in Spotify installed by flatpak.
The error was:
```
Spotify not found in PATH. Searching for Spotify directory...
Spotify directory not found. Set directory path with -P flag.
Exiting...
```

It might be because flatpak version of Spotify is installed in `/var/lib/flatpak/`, Instead of `/usr/bin/`.
So I tried using -P flag in `/var/lib/flatpak/app/com.spotify.Client`.
Then the output was:
```
No xpui found in directory provided with -P.
Please confirm directory and try again or re-install Spotify.
Exiting...
```
I tried to search for xpui, and what I found is `xpui.spa` inside `/var/lib/flatpak/app/com.spotify.Client/x86_64/stable/33a8119a0b42716946ae2bb0ac43c8e34e4522b8623b9dc818bbd6576ac88194/files/extra/share/spotify/Apps`.
Then I tried to run the script in that folder, but the script still did not find any xpui file:
```
No xpui found in directory provided with -P.
Please confirm directory and try again or re-install Spotify.
Exiting...

curl: (23) Failure writing output to destination
```

### 🖵 Terminal Output

```
Spotify not found in PATH. Searching for Spotify directory...
Spotify directory not found. Set directory path with -P flag.
Exiting...
```

**Comment by jetfir3** [comment]
> 
> I tried to search for xpui, and what I found is `xpui.spa` inside `/var/lib/flatpak/app/com.spotify.Client/x86_64/stable/33a8119a0b42716946ae2bb0ac43c8e34e4522b8623b9dc818bbd6576ac88194/files/extra/share/spotify/Apps`. Then I tried to run the script in that folder, but the script still did not find any xpui file:
> 

@frnmz 
you're to set the `spotify` directory path, not `spotify/Apps` path. Drop `/Apps`.

**Comment by r0xANDt0l** [comment]
Sorry for necroposting, but I think it would be a good idea to leave the command for flatpak install, so it's easier to check it for new users
