### ISSUE TITLE
zip was not found, exiting... 

### ISSUE THREAD

**Issue by m-jishnu** [SpotX-CLI/SpotX-Linux#22]
i have a debian 11 system, installed spotify through apt when running the command its showing this 
![image](https://user-images.githubusercontent.com/83004520/209355268-66631f17-7b5a-44c2-92f6-2ee78b651c6a.png)

**Comment by jetfir3** [comment]
SpotX-Linux `install.sh` script has 3 dependencies it checks for before running, `perl`, `unzip` and `zip`. 

The output indicates that you are missing at least the zip package on your system -- install it via `apt` or however else you install things.

**Comment by m-jishnu** [comment]
thanks for the help, i thought it was not finding the path of the spotify app and i did something wrong during the installation
