### ISSUE TITLE
Lyrics not showing

### ISSUE THREAD

**Issue by galaxian01** [SpotX-CLI/SpotX-Linux#25]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of Spotify and SpotX

### Сountry of your account

Australia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.1.84.716
- Distro: Garuda Linux
- Shell: fish 3.5.1
```

### 📝 Description

Installing the script is perfectly fine, and no ads are to be seen, but when launching there is no more lyrics. Existing issue already was "resolved", but the "fix" does not fix the issue.

### 🖵 Terminal Output

**************************
SpotX-Linux by @SpotX-CLI
**************************

SpotX-Linux version: 1.2.1.968-1

Spotify directory found in PATH: /opt/spotify
/opt/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/spotify/spotify)

Spotify version:  1.1.84.716

Creating xpui backup...
Extracting xpui...
Applying SpotX patches...
Removing ad-related content...
Removing premium-only features...
Unlocking Spotify Connect...
Removing logging...
Rebuilding xpui...
SpotX finished patching!

### 📸 Screenshots

![Screenshot_Spotify_4](https://user-images.githubusercontent.com/121745673/210163931-1c2ca0cf-b1af-4216-8830-47ab178f9e79.png)

look in bottom right hand corner*

**Comment by jetfir3** [comment]
You didn't share terminal input as requested in template but it seems `-e` was not used which may be required if lyrics are not showing for you.. as the "fix" is in the experimental patches subset. And since SpotX was already ran, you'd also need the `-f` flag to force a re-patch.

**Comment by galaxian01** [comment]
typing in multiple flags does not work? like for example when i add `-e -f` to the command, it does not register the flags.

**Comment by jetfir3** [comment]
> typing in multiple flags does not work? like for example when i add `-e -f` to the command, it does not register the flags.

as already shown in the example in the `readme`, combine them: `-ef`

**Comment by galaxian01** [comment]
sorry but adding both flags still does not work? still no lyrics show...

**Comment by jetfir3** [comment]
I would suspect this is due to cached app data conflicting with the new settings. you can try re-running SpotX with the `-cef` flags and have SpotX attempt to clear Spotify app data.. 

but due to so many file location variables with Spotify on Linux it may notbe able to find the proper location where app cache is located on your system. And in that case you would need to manually locate your Spotify cache folder and delete it. By default, the location SpotX looks for app cache is `CACHE_PATH="${HOME}/.cache/spotify/"`.

**Comment by galaxian01** [comment]
i get `bash: -c: option requires an argument` when trying to add `-cef` argument.

also tried deleting cache folder and reinstalling but still no change.
