### ISSUE TITLE
No xpui found in directory provided with -P.

### ISSUE THREAD

**Issue by electriquo** [SpotX-CLI/SpotX-Linux#47]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of Spotify and SpotX

### Сountry of your account

United States

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.29.605.g66a43ceb
- Distro: macOS 14.2.1
- Shell: BASH 5.2.26
```

### 📝 Description

```shell
bash <(curl -sSL https://raw.githubusercontent.com/SpotX-CLI/SpotX-Linux/main/install.sh) -cefP ~/Applications/Spotify.app
```

### 🖥️ Terminal Input/Output

```shell
**************************
SpotX-Linux by @SpotX-CLI
**************************

SpotX-Linux version: 1.2.3.1115-1

No xpui found in directory provided with -P.
Please confirm directory and try again or re-install Spotify.
Exiting...
```

I also tried as recommended, reinstalling Spotify, with the same result.

**Comment by yqlbu** [comment]
I am experiencing the same issue, any idea?

**Comment by Nuzair46** [comment]
@electriquo the reason this patch still fails is that I dont have access to a linux distro to test.
If you are able to contribute, you can follow whats being done here for the macOS app. Its similar except for the paths.
https://github.com/Nuzair46/BlockTheSpot-Mac/blob/main/install.sh

**Comment by LuluW8071** [comment]
@electriquo install from official website first then use curl command from `README.md`. You probably faced issue since u installed from using `sudo snap`
