### ISSUE TITLE
Spotify from Pop!_Shop does not work with SpotX-Linux.

### ISSUE THREAD

**Issue by slash1div** [SpotX-CLI/SpotX-Linux#7]
![image](https://user-images.githubusercontent.com/83387831/197426393-429b5c0e-b696-4353-b87c-e03f1b2c855c.png)
Shows this error message. Let me know if you have any alternative downloads for Spotify or a potential fix.

**Comment by jetfir3** [comment]
@slash1div can you share your output of `type -p spotify`?

If the output does not point to Spotify then Spotify is not added to PATH and there's nothing we can do at the moment until we add the ability to manually set Spotify location.

**Comment by jetfir3** [comment]
Issue fixed. Closing -- see previous message for details.
